apiVersion: v1
kind: Secret
metadata:
  name: cosmos-db-secret
type: Opaque
stringData:
  # Kubernetes will automatically base64 encode this string upon apply!
  COSMOS_CONNECTION_STRING: "AccountEndpoint=https://YOUR_COSMOS_ACCOUNT_NAME.documents.azure.com:443/;AccountKey=YOUR_ACCOUNT_KEY;"
